# -*- coding: utf-8 -*-
"""effmtnet_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17U_TTE9M-nut-pe4wWa1dnqhpKRhUark
"""

#라이브러리 뷸러오기
import torch
import torch.nn as nn
import torch.nn.functional as F
import os
import pandas as pd
from torchvision.io import decode_image
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchmetrics.classification import MulticlassConfusionMatrix

import torch.optim as optim

# 모델 준비 (scratch)
model = EffEmoteNetSmall().to(device)

sobel_y = torch.tensor([ #감은 눈의 edge는 ㅡ 모양이기 떄문에 y로 바꿈
    [1., 2., 1.],
    [0., 0., 0.],
    [-1., -2., -1.]
], dtype=torch.float32)

sobel_kernel = sobel_y.unsqueeze(0).repeat(4, 1, 1)
#sobel_kernel = sobel_y.unsqueeze(0).repeat(3, 1, 1)
sobel_kernel = sobel_kernel.unsqueeze(0)

#with torch.inference_mode():
    #model.conv1.weight[0].copy_(sobel_kernel.to(device)[0])
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=1e-3,
    weight_decay=1e-4
)

from transformers import get_cosine_schedule_with_warmup

epochs = 20
num_training_steps = len(train_loader) * epochs
num_warmup_steps = len(train_loader) * 3  # 3 epoch warmup

scheduler = get_cosine_schedule_with_warmup(
    optimizer,
    num_warmup_steps=num_warmup_steps,
    num_training_steps=num_training_steps
)

# 학습 루프
for epoch in range(epochs):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Train Loss: {total_loss/len(train_loader):.4f}")

    # 검증
    model.eval()
    metric.reset()
    correct, total = 0, 0
    with torch.inference_mode() :
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)
            metric.update(preds, labels)
    print(f"Validation Accuracy: {correct/total:.4f}")

import torch
import time
import numpy as np

# 1. 모델과 데이터 준비
model.eval()

dummy_input = torch.randn(1, 4, 300, 300).to(device)

# 2. Warm-up (초기화 오버헤드 제거)
# GPU가 초기화되고 캐싱되는 시간을 측정에서 제외합니다.
print("Warming up...")
with torch.no_grad():
    for _ in range(10):
        _ = model(dummy_input)

# 3. 속도 측정 (CUDA Event 사용 권장)
starter, ender = torch.cuda.Event(enable_timing=True), torch.cuda.Event(enable_timing=True)
repetitions = 100
timings = np.zeros((repetitions, 1))

print("Measuring latency...")
with torch.no_grad():
    for rep in range(repetitions):
        starter.record()
        _ = model(dummy_input)
        ender.record()

        # GPU 동기화: GPU 연산이 끝날 때까지 기다림
        torch.cuda.synchronize()

        curr_time = starter.elapsed_time(ender) # 밀리초(ms) 단위 반환
        timings[rep] = curr_time

mean_syn = np.sum(timings) / repetitions
std_syn = np.std(timings)

print(f"평균 추론 시간(Latency): {mean_syn:.2f} ms")
print(f"표준 편차: {std_syn:.2f} ms")
print(f"초당 처리 프레임(FPS): {1000 / mean_syn:.2f}")

model.eval()
metric.reset()
correct, total = 0, 0
with torch.inference_mode() :
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, preds = torch.max(outputs, 1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)
        metric.update(preds, labels)
print(f"Test Accuracy: {correct/total:.4f}")

# Accuracy 계산
print(f"Accuracy: {correct/total:.4f}")
macro_precision_metric = MulticlassPrecision(num_classes=num_classes, average='macro').to(device)
macro_precision = macro_precision_metric(preds, labels)

# Recall (Macro)
macro_recall_metric = MulticlassRecall(num_classes=num_classes, average='macro').to(device)
macro_recall = macro_recall_metric(preds, labels)

# F1 Score (Macro)
macro_f1_metric = MulticlassF1Score(num_classes=num_classes, average='macro').to(device)
macro_f1 = macro_f1_metric(preds, labels)

print(f"Precision: {macro_precision.item():.4f}")
print(f"Recall: {macro_recall.item():.4f}")
print(f"F1 Score: {macro_f1.item():.4f}")

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Confusion Matrix tensor 얻기
cm = metric.compute().cpu().numpy()

# 클래스 이름(있으면 넣고, 없으면 0~N-1)
class_names = [f"Class {i}" for i in range(cm.shape[0])]

# pandas DataFrame으로 변환
df_cm = pd.DataFrame(cm, index=class_names, columns=class_names)

plt.figure(figsize=(8, 6))
sns.heatmap(df_cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix Heatmap")
plt.show()